name: build tests

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo'
        required: true
        default: 'kuberry/spack'
      ref:
        description: 'ref'
        required: true
        default: 'refs/heads/develop'
        
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.ref }}
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: x64
      
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        
    - name: Source Spack
      run: |
          ls
          . share/spack/setup-env.sh
          spack -d -v -k install xyce+pymi
          
          
