name: build tests

on: 
  workflow_dispatch:
    inputs:
      userbranch:
        description: 'username:branchname'
        required: true
        default: 'kuberry:develop'
        
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest',]
        # 'macos-latest']
        
    steps:
    - id: get-branch-ref
      run: |
        user=$(echo ${{ github.event.inputs.userbranch }} | cut -d: -f1)
        branch=$(echo ${{ github.event.inputs.userbranch }} | cut -d: -f2)
        echo "::set-output name=user::$user"
        echo "::set-output name=branch::$branch"
    
    - uses: actions/checkout@v2
      with:
        repository: ${{steps.get-branch-ref.outputs.user}}/spack
        ref: refs/heads/${{steps.get-branch-ref.outputs.branch}}
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
      
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        
    - name: Source Spack
      run: |
          ls
          . share/spack/setup-env.sh
          spack -d -v -k install xyce+pymi
          
          
